apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
#to execute this yaml type:
# kubectl apply wordpress-presistancevolumeclaim.yaml
