apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  ports:
  - port: 80
  type: LoadBalancer
# to execute this type:
#kubectl apply wordpress-loadbalancer.yaml
